 version: 2
 jobs:
   one:
     docker:
       - image: circleci/ruby:2.4.1
     environment:
        SENTRY_ORG: liz
        SENTRY_PROJECT: buggy-sentry-project
        SENTRY_DEPLOY_ENVIRONMENT: circleci-test1
     steps:
       - checkout
       - run:
            command: |
              echo "A first hello"
              echo $SENTRY_ORG
              echo $SENTRY_PROJECT
              echo $SENTRY_DEPLOY_ENVIRONMENT
              echo $SENTRY_AUTH_TOKEN
              export BLAH=test123
              echo $BLAH
   two:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "Job two says hi!"
 workflows:
   version: 2
   "one_and_two":
     jobs:
       - one
