 version: 2
 jobs:
   one:
     docker:
       - image: circleci/ruby:2.4.1
     environment:
        SENTRY_ORG: liz
        SENTRY_PROJECT: buggy-sentry-project
        SENTRY_DEPLOY_ENVIRONMENT: circleci-test1
     steps:
       - checkout
       - run: echo "A first hello"
       - run: echo $SENTRY_ORG
       - run: echo $SENTRY_PROJECT
       - run: echo $SENTRY_DEPLOY_ENVIRONMENT
       - run: echo $SENTRY_AUTH_TOKEN
       - run: export NEWVAR="hello"
       - run: export NEWVARTWO=(echo "helloagain")
       - run: echo $NEWVAR
       - run: echo $NEWVARTWO
         # - run: curl -sL https://sentry.io/get-cli/ | bash
         # - run: export SENTRY_RELEASE=$(sentry-cli releases propose-version)
         # - run: sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
         # - run: sentry-cli releases set-commits --auto $SENTRY_RELEASE
         # - run: sentry-cli releases finalize $SENTRY_RELEASE

   two:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "Job two says hi!"
 workflows:
   version: 2
   "one_and_two":
     jobs:
       - one
